#!/bin/bash

. ./packaging.conf

# ------ Revert debian/changelog and debian/control -------------------------
# git checkout debian/changelog configure.ac


# ------ Current GIT version ------------------------------------------------
CHANGELOG_HEADER="`head -n1 debian/changelog`"

# The package name, e.g. MyApplication
PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
# The package distribution, e.g. precise, raring, ...
PACKAGE_DISTRIBUTION=`echo $CHANGELOG_HEADER | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`
# The package's version, e.g. 1.2.3-1ubuntu1
PACKAGE_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g" -e "s/^[0-9]://g" -e "s/+.*//g"`
# The package's output version, e.g. 1.2.3-1ubuntu
OUTPUT_VERSION=`echo $PACKAGE_VERSION   | sed -e "s/\(ubuntu\|ppa\)[0-9]*$/\1/"`
# The package's Debian version, e.g. 1.2.3-1
DEBIAN_VERSION=`echo $OUTPUT_VERSION    | sed -e "s/\(ubuntu\|ppa\)$//1"`
# The package's upstream version, e.g. 1.2.3
UPSTREAM_VERSION=`echo $DEBIAN_VERSION  | sed -e "s/-[0-9]*$//"`
# The package's plain upstream version, e.g. 1.2.3 (without e.g. ~svn<xxxx>)
PLAIN_VERSION=`echo $UPSTREAM_VERSION   | sed -e "s/\([0-9\.]*\)[-+~].*$/\1/"`

VERSION=`git describe --tags --long | sed -e "s#debian/##g" -e "s#-g\([0-9a-f]*\)#+g\`env LANG=en date -u +"%Y%m%d%H%M"\`~\1#g"`


# ------ Change Makefile ----------------------------------------------------
sed "s#VERSION := \".*\"#VERSION := \"${VERSION}\"#g" <Makefile >Makefile.new

# ------ Create debian/changelog --------------------------------------------
(
   echo "iproute2 (${VERSION}-1ppa1) unstable; urgency=medium"
   echo ""
   echo "  * Self-made package"
   echo ""
   echo " -- $MAINTAINER  `env LANG=en date +"%a, %02d %b %Y %H:%M:%S %z"`"
) | tee debian/changelog.new


# ------ Apply changes ------------------------------------------------------
mv Makefile.new Makefile
mv debian/changelog.new debian/changelog
